# Generated by Django 4.2.16 on 2024-11-07 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='شماره موبایل باید دقیقا ۱۱ رقم باشد.', regex='^\\d{11}$')]),
        ),
    ]
