version: '3.8'

services:
  web:
    build: .
    container_name: django_chat_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=chat_db
      - DATABASE_USER=chat_user
      - DATABASE_PASSWORD=chat_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
