# Generated by Django 4.2.16 on 2024-11-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
