# Generated by Django 4.2.16 on 2024-11-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
